### PR TITLE
Small modifications in the menu and some Dutch (NL) translations.

### PR DESCRIPTION
**Pull request by STemplar**
- locales/messages.pot: added the msgid "Track gauge".
- locales/nl_NL/LC_MESSAGES/messages.po: modified 1 and added another translation.
- js/bitmap-map.js: removed the " (beta)" text.
- js/mobile.js: removed the " (beta)" text.

### CODE REVIEW

**Comment by DerDakon** [comment]
@JJJWegdam can you have a look please?

**Comment by JJJWegdam** [comment]
@STemplar at the Dutch railways the word “Treinbeveiliging” is preferred over “Treinbeïnvloeding” (while the latter is not necessarily wrong)

**Comment by STemplar** [comment]
> @STemplar at the Dutch railways the word “Treinbeveiliging” is preferred over “Treinbeïnvloeding” (while the latter is not necessarily wrong)

Corrected and some more.

**Review by Nakaner — APPROVED** [review]

**Comment by DerDakon** [comment]
Since I merged another change to the .po files that renamed the signal layer please rebase, afterwards we can merge it.

**Comment by STemplar** [comment]
> Since I merged another change to the .po files that renamed the signal layer please rebase, afterwards we can merge it.

Did I properly rebased it? I have never done that before. Or is it the pending review which is necessary for a merge?

**Comment by DerDakon** [comment]
looks like you have merged master into your branch, but did no rebase. If you need help with that please join #OpenRailwayMap channel on OFTC so we can solve this.

**Review by DerDakon — APPROVED** [review]

**Pull request merged**
