### PR TITLE
Move PHP files out of api directory

### PR DESCRIPTION
**Pull request by mmoll**

### CODE REVIEW

**Comment by mmoll** [comment]
The legend generator is responding with HTML, not an API response, so IMHO this is reasonable.

This would open up the path to extract the current NodeJS API into its own repo and also to seperate out its deployment. I have the beginning of surface testing the API in my branch `api_tests` here: https://github.com/mmoll/OpenRailwayMap/actions/runs/572702320

All this would make the API deployable standalone or also containerized and also facilitate the future switch to i.e. the Python rewrite.

**Comment by mmoll** [comment]
I just found a fix locally for the non-working locales also, but it would require all the PHP files to be in the same directory...

**Review by Nakaner — APPROVED** [review]

**Comment by DerDakon** [comment]
So, does this still need any additional things to get the localization working? Or is everything ready?

**Comment by mmoll** [comment]
Everything is ready. :)

**Pull request merged**
