### PR TITLE
Added support for Dutch ETCS block markers

### PR DESCRIPTION
**Pull request by JJJWegdam**
(new version of [PR701](https://github.com/OpenRailwayMap/OpenRailwayMap/pull/701))

etcs-stop-marker-arrow-left-32 etcs-stop-marker-triangle-left-32

- edited signals.mapcss
- added etcs-stop-marker-triangle-left.svg to icons
- added etcs-stop-marker-triangle-left-32.png to icons

### CODE REVIEW

**Comment by JJJWegdam** [comment]
On the mailing list Eike proposed the new tag `railway:signal:<category>:shape`. This followed from the fact that the Dutch 227b signal has two different signs that are both acknowledged in the Dutch law.

**Comment by JJJWegdam** [comment]
(double checked everything and added `*/` at the end of `./styles/signals.mapcss` line 1014, which I had forgotten earlier on)

**Comment by DerDakon** [comment]
I assume you have tested both signal styles with JOSM?

**Comment by JJJWegdam** [comment]
Yes. The only thing that was strange was text offset. It is set to 12 for all other similar signals, while in JOSM the text offset 0 works best for me. I don't know why

**Review by DerDakon — APPROVED** [review]

**Pull request merged**
