### PR TITLE
Add rendering GSM-R masts

### PR DESCRIPTION
**Pull request by Nakaner**
The icon lacks some creativity but it was fast to draw.

@bigbug21 might be interested in rendering of these masts.

### CODE REVIEW

**Comment by bigbug21** [comment]
Thanks. It would be somewhat nice to see GSM-R masts on the map. In addition, it would be good if GSM-R antennas (such as on tunnel portals) would be shown as well. They are usually mapped with "man_made=antenna" and the usual GSM-R tags. (Perhaps this could be added to the templates as well)

**Comment by Nakaner** [comment]
Dakon commented on the IRC that the icon looks more like a Lf 7 signal seen from its back side than a radio mast with antennas. That's why I drew a new icon.

Radio mast:

radio-mast-30

[Radio antenna](https://commons.wikimedia.org/wiki/File:GSMRRichtantennenFreudensteintunnelOst.jpg) as whished by @bigbug21:

radio-antenna-20

**Comment by rurseekatze** [comment]
The new icons look much better. The old one really looks like the back side of a sign. Can you add the new icons to the style?

**Comment by Nakaner** [comment]
I applied the changes, squashed the commits and rebased onto master.

**Comment by Nakaner** [comment]
I rebased on current master and would appreciate a merge because I have been asked for progress on this issue.

**Comment by rurseekatze** [comment]
You could also include the new icons in the JOSM preset.

**Comment by rurseekatze** [comment]
The icon is not very readable because the underlying background map also renders communication masts with a similar icon:
screenshot at 2018-08-27 20 21 50

@Nakaner might it be better to replace the icon by [the one used in openstreetmap-carto](https://github.com/gravitystorm/openstreetmap-carto/blob/master/symbols/towers/communications_tower.svg)?

**Comment by Nakaner** [comment]
@rurseekatze Or adding white rectangular casing similar to the `railway=phone` icon?

**Comment by rurseekatze** [comment]
Yes, that is also a good solution. I think this would also be better readable than a thin black icon on a gray background. Please propose a version with some casing (round or rectangular?).

**Pull request merged**
