### PR TITLE
Updated Swedish translation

### PR DESCRIPTION
**Pull request by KildorSE**
I have added missing translations, and updated/changed some existing translations to better reflect Swedish railway terminology and the current usage of objects on OSM.

### CODE REVIEW

**Comment by DerDakon** [comment]
Please squash the 2 commits together if the latter is just another fixup.

**Comment by KildorSE** [comment]
> Please squash the 2 commits together if the latter is just another fixup.

Sorry, I am new to Github. How do I do that? I thought the PR includes all the changes (2) I made to the file. And when I look at the tab "file changed", I can see that both the edits are included. Any help/directions here are welcome!

**Comment by DerDakon** [comment]
`´´
git reset HEAD^
git commit ---amend -aS --no-edit
```

**Comment by KildorSE** [comment]
> ```
> git reset HEAD^
> git commit ---amend -aS --no-edit
> ```

Hmm... I have made all changes through the web editor. So any ideas on how I can do this using the web editor? (And I still don't understand the problem with the two commits).

**Comment by DerDakon** [comment]
np then.

**Review by DerDakon — APPROVED** [review]

**Pull request merged**
