### PR TITLE
standard style: handle subway and light_rail stations separately

### PR DESCRIPTION
**Pull request by DerDakon**
Handles the first part of #627.

### CODE REVIEW

**Comment by rurseekatze** [comment]
The code is ok, but I wonder if it is a good idea to use cursive font to distinguish between train stations and subway/light rail stations. Cursive font 

Maybe it is better to use non-cursive and non-bold font and use the font color to distinguish the type of stations. Light rail stations could be rendered with green font and subway stations with blue font. In that case it would be necessary to change the font color of train stations to black.

**Comment by DerDakon** [comment]
I decided against that because green text has rather low contrast, and is probably unreadable for some people.

**Comment by DerDakon** [comment]
ping

**Comment by DerDakon** [comment]
I messed it up…

**Pull request closed without merging**
