### PR TITLE
KVB and TVM (french system) added

### PR DESCRIPTION
**Pull request by Sovxx**
Hi,
I have added this https://en.wikipedia.org/wiki/Contr%C3%B4le_de_vitesse_par_balises
in pale green.

Please double check (I am a noob programer !)

### CODE REVIEW

**Comment by DerDakon** [comment]
Don't add the translation to all the message files, just add the msgid, and ```msgstr ""```. In case the msgstr is empty the translation software will use the original string anyway.

**Comment by Sovxx** [comment]
thx, done

**Comment by Nakaner** [comment]
@Sovxx, thank you for the contribution.

I haven't tested it in JOSM yet (nor ported to the CartoCSS style). Other systems have long names that match their abbreviation. Was the long name of KVB changed in the past without changing the abbreviation? Or why do the abbreviation and the long name differ? I am just curious.

**Comment by Sovxx** [comment]
Yes, the abbreviation should have been CVB.
But the reason is explained here:
https://fr.wikipedia.org/wiki/Contr%C3%B4le_de_vitesse_par_balises
https://en.wikipedia.org/wiki/Contr%C3%B4le_de_vitesse_par_balises
The letter C could have been confused with "commande" (as if the system was actively driving the train), so SNCF chose the letter K for contrôle (the system checks the speed is okay).
A bit weird ;)

**Review by Nakaner — APPROVED** [review]

**Comment by DerDakon** [comment]
Can you please rebase this, and while at it squash the first 2 commits together?

**Comment by Sovxx** [comment]
I have resolved the conflict, but I don't know how to do the squash thing on the KVB branch of my fork...

**Comment by DerDakon** [comment]
You also introduced a "missing newline at end of file" in the Svedish translation.

For squashing (in fact you should use fixup) a description can be found here: https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History

**Comment by Sovxx** [comment]
I have fixed the missing new line, but I get some conflict when trying :
```
pick 9599db4
squash 76ccf6b
```
sorry, but I prefer not to go further because I think I would make it even messier !

**Comment by DerDakon** [comment]
You can fetch from the main repository and then reset to the KVB branch in that repository. There I have rebased everything on the current master branch.

**Comment by Sovxx** [comment]
I have "fetched" both master and KVB branches on my fork.
I am confused by the reset thing.
I don't know if it is correct...
Otherwise, I may give up... sorry

**Comment by DerDakon** [comment]
```shell
git reset --hard OpenRailwayMap/KVB
git push --force
```

**Comment by Sovxx** [comment]
I don't know what is wrong :
```
benoit@benoit-MS-7971:~/github/OpenRailwayMap$ git reset --hard OpenRailwayMap/KVB
fatal: argument 'OpenRailwayMap/KVB' ambigu : révision inconnue ou chemin inexistant.
Utilisez '--' pour séparer les chemins des révisions, comme ceci :
'git <commande> [<révision>...] -- [<chemin>...]'
benoit@benoit-MS-7971:~/github/OpenRailwayMap$ git status
Sur la branche master
Votre branche est à jour avec 'origin/master'.

rien à valider, la copie de travail est propre
benoit@benoit-MS-7971:~/github/OpenRailwayMap$ git branch
  OpenRailwayMap-master
* master
benoit@benoit-MS-7971:~/github/OpenRailwayMap$ git branch -a
  OpenRailwayMap-master
* master
  remotes/origin/HEAD -> origin/master
  remotes/origin/KVB
  remotes/origin/database-changelog
  remotes/origin/master
  remotes/origin/quality-assurance
  remotes/origin/uikit-website
  remotes/origin/update-translations
  remotes/origin/website-redesign
benoit@benoit-MS-7971:~/github/OpenRailwayMap$ git clone --branch KVB https://github.com/Sovxx/OpenRailwayMap.git
Clonage dans 'OpenRailwayMap'...
remote: Enumerating objects: 11264, done.
remote: Counting objects: 100% (60/60), done.
remote: Compressing objects: 100% (30/30), done.
remote: Total 11264 (delta 21), reused 43 (delta 15), pack-reused 11204
Réception d'objets: 100% (11264/11264), 8.41 Mio | 19.53 Mio/s, fait.
Résolution des deltas: 100% (6407/6407), fait.
benoit@benoit-MS-7971:~/github/OpenRailwayMap$ git branch -a
  OpenRailwayMap-master
* master
  remotes/origin/HEAD -> origin/master
  remotes/origin/KVB
  remotes/origin/database-changelog
  remotes/origin/master
  remotes/origin/quality-assurance
  remotes/origin/uikit-website
  remotes/origin/update-translations
  remotes/origin/website-redesign
benoit@benoit-MS-7971:~/github/OpenRailwayMap$ git reset --hard OpenRailwayMap/KVB
fatal: argument 'OpenRailwayMap/KVB' ambigu : révision inconnue ou chemin inexistant.
Utilisez '--' pour séparer les chemins des révisions, comme ceci :
'git <commande> [<révision>...] -- [<chemin>...]'
benoit@benoit-MS-7971:~/github/OpenRailwayMap$ git branch
  OpenRailwayMap-master
* master
benoit@benoit-MS-7971:~/github/OpenRailwayMap$ git reset --hard OpenRailwayMap/remotes/origin/KVB
fatal: argument 'OpenRailwayMap/remotes/origin/KVB' ambigu : révision inconnue ou chemin inexistant.
Utilisez '--' pour séparer les chemins des révisions, comme ceci :
'git <commande> [<révision>...] -- [<chemin>...]'
benoit@benoit-MS-7971:~/github/OpenRailwayMap$ git reset --hard "OpenRailwayMap/KVB"
fatal: argument 'OpenRailwayMap/KVB' ambigu : révision inconnue ou chemin inexistant.
Utilisez '--' pour séparer les chemins des révisions, comme ceci :
'git <commande> [<révision>...] -- [<chemin>...]'
benoit@benoit-MS-7971:~/github/OpenRailwayMap$ git fetch
remote: Enumerating objects: 7, done.
remote: Counting objects: 100% (7/7), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 7 (delta 3), reused 6 (delta 3), pack-reused 0
Dépaquetage des objets: 100% (7/7), 1020 octets | 113.00 Kio/s, fait.
Depuis https://github.com/Sovxx/OpenRailwayMap
   fd3cb68..eaabc51  KVB        -> origin/KVB
benoit@benoit-MS-7971:~/github/OpenRailwayMap$ git branch -a
  OpenRailwayMap-master
* master
  remotes/origin/HEAD -> origin/master
  remotes/origin/KVB
  remotes/origin/database-changelog
  remotes/origin/master
  remotes/origin/quality-assurance
  remotes/origin/uikit-website
  remotes/origin/update-translations
  remotes/origin/website-redesign
benoit@benoit-MS-7971:~/github/OpenRailwayMap$ git fetch KVB
fatal: 'KVB' does not appear to be a git repository
fatal: Impossible de lire le dépôt distant.

Veuillez vérifier que vous avez les droits d'accès
et que le dépôt existe.
benoit@benoit-MS-7971:~/github/OpenRailwayMap$ git fetch origin
benoit@benoit-MS-7971:~/github/OpenRailwayMap$ git branch -a
  OpenRailwayMap-master
* master
  remotes/origin/HEAD -> origin/master
  remotes/origin/KVB
  remotes/origin/database-changelog
  remotes/origin/master
  remotes/origin/quality-assurance
  remotes/origin/uikit-website
  remotes/origin/update-translations
  remotes/origin/website-redesign
benoit@benoit-MS-7971:~/github/OpenRailwayMap$ git remote
origin
benoit@benoit-MS-7971:~/github/OpenRailwayMap$ 
```

**Comment by DerDakon** [comment]
Sorry, I was under the impression that you have already the original repository in your local git clone. So, just do this in your normal git dir:

```shell
git remote add OpenRailwayMap https://github.com/OpenRailwayMap/OpenRailwayMap.git
git fetch OpenRailwayMap
git reset --hard OpenRailwayMap/KVB
git push --force
```

**Comment by Sovxx** [comment]
```
benoit@benoit-MS-7971:~/github$ git remote add OpenRailwayMap https://github.com/OpenRailwayMap/OpenRailwayMap.git
fatal: ni ceci ni aucun de ses répertoires parents (jusqu'au point de montage /) n'est un dépôt git
Arrêt à la limite du système de fichiers (GIT_DISCOVERY_ACROSS_FILESYSTEM n'est pas défini).
benoit@benoit-MS-7971:~/github$ cd OpenRailwayMap/
benoit@benoit-MS-7971:~/github/OpenRailwayMap$ git remote add OpenRailwayMap https://github.com/OpenRailwayMap/OpenRailwayMap.git
benoit@benoit-MS-7971:~/github/OpenRailwayMap$ git fetch OpenRailwayMap
remote: Enumerating objects: 15, done.
remote: Counting objects: 100% (15/15), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 15 (delta 11), reused 15 (delta 11), pack-reused 0
Dépaquetage des objets: 100% (15/15), 3.37 Kio | 123.00 Kio/s, fait.
Depuis https://github.com/OpenRailwayMap/OpenRailwayMap
 * [nouvelle branche] KVB                   -> OpenRailwayMap/KVB
 * [nouvelle branche] database-changelog    -> OpenRailwayMap/database-changelog
 * [nouvelle branche] josm-hv-distant-shape -> OpenRailwayMap/josm-hv-distant-shape
 * [nouvelle branche] master                -> OpenRailwayMap/master
 * [nouvelle branche] quality-assurance     -> OpenRailwayMap/quality-assurance
 * [nouvelle branche] uikit-website         -> OpenRailwayMap/uikit-website
 * [nouvelle branche] update-translations   -> OpenRailwayMap/update-translations
 * [nouvelle branche] validator-service-ref -> OpenRailwayMap/validator-service-ref
 * [nouvelle branche] website-redesign      -> OpenRailwayMap/website-redesign
benoit@benoit-MS-7971:~/github/OpenRailwayMap$ git reset --hard OpenRailwayMap/KVB
HEAD est maintenant à a5404af TVM improvement (300 and 430 values)
benoit@benoit-MS-7971:~/github/OpenRailwayMap$ git push --force
Username for 'https://github.com': Sovxx
Password for 'https://Sovxx@github.com': 
Total 0 (delta 0), réutilisés 0 (delta 0)
To https://github.com/Sovxx/OpenRailwayMap.git
 + 1fc36c9...a5404af master -> master (forced update)
```
No error message, but I have no idea if it worked

**Comment by DerDakon** [comment]
You have not been on your KVB branch. To fix the branches you would do:

```shell
git checkout master
git reset --hard OpenRailwayMap/master
git push --force
git checkout KVB
git reset --hard OpenRailwayMap/KVB
git push --force
```

**Comment by Sovxx** [comment]
```
benoit@benoit-MS-7971:~/github/OpenRailwayMap$ git checkout master
Déjà sur 'master'
Votre branche est à jour avec 'origin/master'.
benoit@benoit-MS-7971:~/github/OpenRailwayMap$ git reset --hard OpenRailwayMap/master
HEAD est maintenant à 253d888 Merge pull request #723 from gszy/drop-font-x-mode-bits
benoit@benoit-MS-7971:~/github/OpenRailwayMap$ git push --force
Username for 'https://github.com': Sovxx
Password for 'https://Sovxx@github.com': 
Total 0 (delta 0), réutilisés 0 (delta 0)
To https://github.com/Sovxx/OpenRailwayMap.git
 + a5404af...253d888 master -> master (forced update)
benoit@benoit-MS-7971:~/github/OpenRailwayMap$ git checkout KVB
error: le spécificateur de chemin 'KVB' ne correspond à aucun fichier connu de git
astuce: 'KVB' correspond à plusieurs branches de suivi distant. Nous avons
astuce: trouvé 2 distants avec une référence correspondante. Nous avons essayé
astuce: de résoudre l'argument comme un chemin, sans plus de résultat !
astuce: 
astuce: Si vous souhaitiez extraire une branche de suivi distant sur 'origin',
astuce: par exemple, qualifiez-la complètement avec l'option --track :
astuce: 
astuce:     git checkout --track origin/<nom>
astuce: 
astuce: Si vous souhaitez privilégier un distant particulier lorsque <nom> est
astuce: ambigu, vous pouvez positionner checkout.defaultRemote=origin dans
astuce: votre config.
benoit@benoit-MS-7971:~/github/OpenRailwayMap$ git reset --hard OpenRailwayMap/KVB
HEAD est maintenant à a5404af TVM improvement (300 and 430 values)
benoit@benoit-MS-7971:~/github/OpenRailwayMap$ git push --force
Username for 'https://github.com': Sovxx
Password for 'https://Sovxx@github.com': 
Total 0 (delta 0), réutilisés 0 (delta 0)
To https://github.com/Sovxx/OpenRailwayMap.git
   253d888..a5404af  master -> master
benoit@benoit-MS-7971:~/github/OpenRailwayMap$ 
```
done but there was an error :

error: le spécificateur de chemin 'KVB' ne correspond à aucun fichier connu de git
astuce: 'KVB' correspond à plusieurs branches de suivi distant. Nous avons
astuce: trouvé 2 distants avec une référence correspondante. Nous avons essayé
astuce: de résoudre l'argument comme un chemin, sans plus de résultat !
astuce: 
astuce: Si vous souhaitiez extraire une branche de suivi distant sur 'origin',
astuce: par exemple, qualifiez-la complètement avec l'option --track :
astuce: 
astuce:     git checkout --track origin/<nom>
astuce: 
astuce: Si vous souhaitez privilégier un distant particulier lorsque <nom> est
astuce: ambigu, vous pouvez positionner checkout.defaultRemote=origin dans
astuce: votre config.

means

error: 'KVB' path specifier does not match any file known to git
tip: 'KVB' matches multiple remote tracking branches. We have
tip: found 2 remote with a matching reference. We tried
trick: to solve the argument like a path, without more result!
trick:
tip: If you wanted to extract a remote tracking branch on 'origin',
tip: for example, fully qualify it with the --track option:
trick:
tip: git checkout --track origin / <name>
trick:
tip: If you want to privilege a particular remote when <name> is
tip: ambiguous, you can set checkout.defaultRemote = origin in
tip: your config.

**Comment by DerDakon** [comment]
```shell
export LANG=C
git checkout -b KVB origin/KVB
git reset --hard OpenRailwayMap/KVB
git push --force
```

**Comment by Sovxx** [comment]
```
benoit@benoit-MS-7971:~/github/OpenRailwayMap$ export LANG=C
benoit@benoit-MS-7971:~/github/OpenRailwayMap$ git checkout -b KVB origin/KVB
Branch 'KVB' set up to track remote branch 'KVB' from 'origin'.
Switched to a new branch 'KVB'
benoit@benoit-MS-7971:~/github/OpenRailwayMap$ git reset --hard OpenRailwayMap/KVB
HEAD is now at a5404af TVM improvement (300 and 430 values)
benoit@benoit-MS-7971:~/github/OpenRailwayMap$ git push --force
Username for 'https://github.com': Sovxx
Password for 'https://Sovxx@github.com': 
Total 0 (delta 0), reused 0 (delta 0)
To https://github.com/Sovxx/OpenRailwayMap.git
 + eaabc51...a5404af KVB -> KVB (forced update)
benoit@benoit-MS-7971:~/github/OpenRailwayMap$ 
```

**Comment by JJJWegdam** [comment]
I plan to write a similar PR for OpenRailwayMap-CartoCSS. Is there any way we can implement this PR on this repo first? I don't see why we would not merge this one.

**Comment by Sovxx** [comment]
I am stuck and am a newbie with git, so I don't know what should be done now.
As far as i'm concerned, do what you want :)
Thanks

**Comment by DerDakon** [comment]
We have better tooling for adding translations meanwhile, I'll clean this up and squash the commits during merge.

**Review by DerDakon — APPROVED** [review]

**Comment by JJJWegdam** [comment]
Many thanks @DerDakon

**Pull request merged**
